# https://github.com/hadolint/hadolint?tab=readme-ov-file#rules
ignored:
  - DL3008 # Pin versions in apt get install
  - DL3013 # Pin versions in pip
  - DL3018 # Pin versions in apk add
  - DL3016 # Pin versions in npm
